/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import javax.swing.JOptionPane;
import Modelo.*; //IMPORTA TODAS LAS CLASES DEL PAQUETE MODELO PARA PODER UTILIZARLAS

/**
 *
 * @author casa4
 */
public class panelCargar extends javax.swing.JFrame {

    CPaquetes CP=null;
    /**
     * Creates new form panelCargar
     */
    //CREA EL FORM, SE CREA SOLO CUANDO CREO EL FORMULARIO
    public panelCargar() {
        initComponents();
        CP = new CPaquetes();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccionip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroSecuencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoDeVerificacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        rbtnTCP = new javax.swing.JRadioButton();
        rbtnUDP = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dato (bytes):");

        jLabel2.setText("Direccion IP de destino:");

        jLabel3.setText("Tipo de paquete:");

        jLabel4.setText("Nº de secuencia");

        jLabel5.setText("Codigo de verificacion");

        jLabel6.setText("de errores:");

        jLabel7.setText("Longitud:");

        buttonGroup1.add(rbtnTCP);
        rbtnTCP.setText("TCP");
        rbtnTCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnTCPMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbtnUDP);
        rbtnUDP.setText("UDP");
        rbtnUDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnUDPMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Ingresar nuevo paquete");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Funciones");

        jMenuItem1.setText("Estadisticas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtnTCP)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoDeVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbtnUDP)
                                .addGap(170, 170, 170))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(48, 48, 48))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccionip, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtDato))))
                        .addContainerGap(357, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccionip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtnTCP)
                    .addComponent(rbtnUDP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoDeVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnTCPMouseClicked
        // TODO add your handling code here:
        //CUANDO SELECCIONO EL RADIO BUTTON TCP SE OCULTA LAS OPCIONES DEL UDP
        jLabel7.setVisible(false);
        txtLongitud.setVisible(false);
        //Y SE MUESTRAN LAS DEL TCP
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        txtNumeroSecuencia.setVisible(true);
        txtCodigoDeVerificacion.setVisible(true);
        
       
    }//GEN-LAST:event_rbtnTCPMouseClicked

    private void rbtnUDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnUDPMouseClicked
        // TODO add your handling code here:
        //CUANDO SELECCIONO EL RADIO BUTTON UDP SE MUESTRAN LAS OPCIONES DE ESTE PAQUETE
        jLabel7.setVisible(true);
        txtLongitud.setVisible(true);
        //Y SE OCULTAN LAS OPCIONES DEL PAQUETE TCP
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        txtNumeroSecuencia.setVisible(false);
        txtCodigoDeVerificacion.setVisible(false);
    }//GEN-LAST:event_rbtnUDPMouseClicked
    //CIERRA EL FORMULARIO
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    //SI PRESIONO EL BOTON GUARDAR Y NO HAY NINGUN RADIO BUTTON SELECCIONADO(TCP NI UDP)
    //    
    if(rbtnTCP.isSelected() == false && rbtnUDP.isSelected() == false)
    {
        //MUESTRA UN MENSAJE 
        JOptionPane.showMessageDialog(this, "Seleccione un tipo de dato para ingresar: TCP o UDP");
    }
    else
    {
    try//PROBAR (SI SE ROMPE LO SALTEA)
    {
        //SI EL RADIO BUTTON TCP ESTA SELECCIONADO
        if (rbtnTCP.isSelected()==true)
        {
            //CREA UN PAQUTE TCP, LE DA UN VALOR NULO PORQUE LO ESTOY INICIALIZANDO. Y DECLARO VARIABLES.
            PaqueteTCP T = null;
            int c = 0;
            String di = "";
            int ns = 0;
            int cv = 0;
            //LA VARIABLE C TOMA EL VALOR DEL TXT DATO (QUE ES UN ENTERO)
            c = Integer.parseInt(txtDato.getText());
            //LA VARIABLE DI TOMA EL VALOR DEL TXT DIRECCION (QUE ES UN STRING)
            di = txtDireccionip.getText();
            //LA VARIABLE NS TOMA EL VALOR DEL TXT NUMERO (QUE ES UN ENTERO)
            ns = Integer.parseInt(txtNumeroSecuencia.getText());
            //LA VARIABLE CV TOMA ELVALOR DEL TXT CODIGO VERIFICACION (QUE ES UN ENTERO)
            cv = Integer.parseInt(txtCodigoDeVerificacion.getText());
            //LE PASA TODAS LAS VARIABLES AL CONSTRUCTOR
            T = new PaqueteTCP(c, di, ns, cv);
            CP.agregar(T);//AGREGA EL PAQUETE T A UNA COLECCION DE PAQUETES (CP)
            JOptionPane.showMessageDialog(this, "El paquete TCP fue sido cargado correctamente, sus valores son: " + T.toString());
            jTextArea2.setText(T.toString()); //MUESTRA UN MENSAJE
        
        }
        //SI EL RADIO BUTTON UDP ESTA SELECCIONADO
        if(rbtnUDP.isSelected() == true)
        {
            //CREA UN PAQUTE UDP, LE DA UN VALOR NULO PORQUE LO ESTOY INICIALIZANDO. Y DECLARO VARIABLES.
            PaqueteUDP U =null;
            int co = 0;
            String dip = "";
            int l = 0;
            //LA VARIABLE CO TOMA EL VALOR DEL TXT DATO (QUE ES UN ENTERO)
            co = Integer.parseInt(txtDato.getText());
            //LA VARIABLE DIP TOMA EL VALOR DEL TXT DIRECCION IP (QUE ES UN STRING)
            dip = txtDireccionip.getText();
            //LA VARIABLE l TOMA EL VALOR DEL TXT LONGITUD (QUE ES UN ENTERO)
            l = Integer.parseInt(txtLongitud.getText());
            //LE PASA TODAS LAS VARIABLES AL CONSTRUCTOR
            U = new PaqueteUDP(co, dip, l);
            CP.agregar(U); //AGREGA EL PAQUETE U A UNA COLECCION DE PAQUETES (CP)
            JOptionPane.showMessageDialog(this, "El paquete UDP fue sido cargado correctamente, sus valores son: " + U.toString());
            jTextArea2.setText(U.toString());//MUESTRA UN MENSAJE
        }
    
    }
    catch(Exception e) //SI ENCUENTRA UN ERROR , MUESTRA EL MENSAJE DE ABAJO
    {
        JOptionPane.showMessageDialog(this, "Los Valores ingresados no son correctos");
    }
    
    LimpiarCajas(); //REFRESCA LAS CAJAS
    
    }
        
        
     
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        panelFuncion1 mostrar = new panelFuncion1(); //CREA UNA VENTANA PANELFUNCION1
        mostrar.setVisible(true); // LA SETEA PARA QUE SEA VISIBLE
        mostrar.getPaquete(CP); // LE ASIGNA AL PANEL LA COLECCION DE PAQUETES PARA QUE SE MUESTREN
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //REFRESCA LAS CAJAS DE TEXTO
    private void LimpiarCajas()
    {
      txtCodigoDeVerificacion.setText("");
      txtDato.setText("");
      txtDireccionip.setText("");
      txtLongitud.setText("");
      txtNumeroSecuencia.setText("");
      txtDato.grabFocus();
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelCargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton rbtnTCP;
    private javax.swing.JRadioButton rbtnUDP;
    private javax.swing.JTextField txtCodigoDeVerificacion;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextField txtDireccionip;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtNumeroSecuencia;
    // End of variables declaration//GEN-END:variables
}
